NumPy Basics

In [2]:
import numpy as np
import time

In [3]:
arr1 = np.array([12 ,34 , 56 , 8])
print(arr1)

[12 34 56  8]


In [4]:
array = np.array([12 , 34, 45,89 , 30])
list = [ 1, 2 ,3 , 4 ,5]
print(array.dtype)
print(type(array))
print(type(list))

int64
<class 'numpy.ndarray'>
<class 'list'>


In [5]:
identity_metrix = np.eye(3 , 3)
print(identity_metrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
zero = np.zeros(4)
print(zero)

[0. 0. 0. 0.]


In [7]:
ones = np.ones(3)
print(ones)

[1. 1. 1.]


In [8]:
two_dim_ones = np.ones([3 , 3])
print(two_dim_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
lin = np.linspace(1 , 10 , 4)
print(lin)

[ 1.  4.  7. 10.]


In [10]:
two_zero = np.zeros([2 , 2])
print(two_zero)

[[0. 0.]
 [0. 0.]]


In [12]:
arr4 = np.arange(1 , 10)
print(arr4)

[1 2 3 4 5 6 7 8 9]


In [14]:
arr4.reshape(3 , 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr4.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
print(arr4.reshape(3 , 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
print(arr4.transpose())

[1 2 3 4 5 6 7 8 9]


In [22]:
print(arr4.transpose())

[1 2 3 4 5 6 7 8 9]


In [24]:
arr5 = np.array([
    [1 , 2 , 3],
    [4 , 5 , 6],
    [7 , 8 , 9]
])

In [25]:
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(arr5.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [28]:
print(arr4[-3:-1:])

[7 8]


In [31]:
print(arr5[::-1,1:3])

[[8 9]
 [5 6]
 [2 3]]


In [32]:
print(arr5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
print(arr5[::-1,::-1])

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [35]:
print(arr5[::2,1::])

[[2 3]
 [8 9]]


In [36]:
print(arr5[::-1,::-2])

[[9 7]
 [6 4]
 [3 1]]


In [37]:
feature_set_1 = np.array([[1 , 2],[3 , 4]])
feature_set_2 = np.array([[5 , 6] ,[7 , 8]])
combined_rows = np.concatenate((feature_set_1 , feature_set_2), axis = 0)
print("Combined vertically (axis = 0):\n",combined_rows)



Combined vertically (axis = 0):
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [38]:
third_arr = np.array([
    [[3, 5, 6],[7, 8, 9]],
    [[4, 9, 3],[9, 7, 6]]
    ])

In [39]:
print(third_arr)

[[[3 5 6]
  [7 8 9]]

 [[4 9 3]
  [9 7 6]]]


In [40]:
print(third_arr[::-1,::-1,::-1])

[[[6 7 9]
  [3 9 4]]

 [[9 8 7]
  [6 5 3]]]


In [44]:
combined_columns = np.concatenate((feature_set_2 , feature_set_1), axis = 1)
print("Combined columns\n",combined_columns)


Combined columns
 [[5 6 1 2]
 [7 8 3 4]]


In [48]:

bias_column = np.ones((2 ,1))
X_bias = np.hstack(bias_column)
print(X_bias)


[1. 1.]


In [49]:
arr_full = np.full(5 , 10)

In [50]:
print(arr_full)

[10 10 10 10 10]


In [51]:
arr1 = np.array([1 , 2 , 3 , 4 , 5])
arr2 = np.array([[5] ,[5] ,[5] ,[5] ,[5]])
print(arr1 + arr2)

[[ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]]


In [52]:
print(arr1.argmax())

4


In [53]:
print(arr2.argmin())

0


In [ ]:
A = np.array([12 , 13 , 12])
B = np.array([23 , 34 , 56])
print(np.dot(A , B))
#he dot product means:
# Multiply corresponding elements and then add all the results.

1390


In [55]:
A = np.var(arr1)
print(A)

2.0


In [75]:
np.random.seed(42)  # this breack the changing number of randomness
rng = np.random.randint(50 , 100 ,3 )
print(rng)
# Syntax is randint = np.random.randint(start , end, count_number to generated)

[88 78 64]
